# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

izhikevich <- function(V, U, I, pars) {
    .Call('_SSGLM_izhikevich', PACKAGE = 'SSGLM', V, U, I, pars)
}

log_logistic <- function(x, a, b) {
    .Call('_SSGLM_log_logistic', PACKAGE = 'SSGLM', x, a, b)
}

rev_vec <- function(x) {
    .Call('_SSGLM_rev_vec', PACKAGE = 'SSGLM', x)
}

mpfpp_cpp <- function(y, x, Bb, Br, Sb, Sr, xpars, s_lag_in, Neffpct, M, w0, q, dt, usetrue, verbose) {
    .Call('_SSGLM_mpfpp_cpp', PACKAGE = 'SSGLM', y, x, Bb, Br, Sb, Sr, xpars, s_lag_in, Neffpct, M, w0, q, dt, usetrue, verbose)
}

px_x <- function(x, pars) {
    .Call('_SSGLM_px_x', PACKAGE = 'SSGLM', x, pars)
}

py_xy <- function(x, y, l0, l1) {
    .Call('_SSGLM_py_xy', PACKAGE = 'SSGLM', x, y, l0, l1)
}

resample <- function(w) {
    .Call('_SSGLM_resample', PACKAGE = 'SSGLM', w)
}

sample_x <- function(x, pars) {
    .Call('_SSGLM_sample_x', PACKAGE = 'SSGLM', x, pars)
}

sim_ssglm <- function(nsim, r0, rk, b0, bk, xpars, dt) {
    .Call('_SSGLM_sim_ssglm', PACKAGE = 'SSGLM', nsim, r0, rk, b0, bk, xpars, dt)
}

test <- function(p) {
    .Call('_SSGLM_test', PACKAGE = 'SSGLM', p)
}

test_input <- function(y) {
    .Call('_SSGLM_test_input', PACKAGE = 'SSGLM', y)
}

